---
title: "Data_Retrieval"
author: "Jake Greif"
date: "7/11/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
## Load Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
install.packages("dataRetrieval")
library(dataRetrieval)
#vignette("dataRetrieval",package = "dataRetrieval")
```

## Haw River at Haw River, NC 
```{r}
siteNo1 <- "02096500"
pCode1 <- "00060"
start.date1 <- "1999-01-01"
end.date1 <- ""

Haw1 <- readNWISdv(siteNumbers = siteNo1,
                     parameterCd = pCode1,
                     startDate = start.date1,
                     endDate = end.date1)

Haw1 <- renameNWISColumns(Haw1)

view(Haw1)
```

## Haw River near Bynum, NC
```{r}
siteNo2 <- "02096960"
pCode2 <- "00060"
start.date2 <- "1999-01-01"
end.date2 <- ""

Haw2 <- readNWISdv(siteNumbers = siteNo2,
                     parameterCd = pCode2,
                     startDate = start.date2,
                     endDate = end.date2)

Haw2 <- renameNWISColumns(Haw2)

view(Haw2)
```

## Site Attribute URLs
```{r}
Haw1_att <- attr(Haw1, "url")
Haw1_att

Haw2_att <- attr(Haw2, "url")
Haw2_att
```

## Data Exploration
```{r}
Haw1_p_Info <- attr(Haw1, "variableInfo")
Haw1_site_Info <- attr(Haw1, "siteInfo")
  
Haw1_Plot <- ggplot(Haw1, aes(Date, Flow)) +
         geom_line() +
         xlab("Year") +
         ylab(Haw1_p_Info$variableDescription) +
         ggtitle(Haw1_site_Info$station_nm)

Haw2_p_Info <- attr(Haw2, "variableInfo")
Haw2_site_Info <- attr(Haw2, "siteInfo")
  
Haw2_Plot <- ggplot(Haw2, aes(Date, Flow)) +
         geom_line() +
         xlab("Year") +
         ylab(Haw2_p_Info$variableDescription) +
         ggtitle(Haw2_site_Info$station_nm)

Haw1_Plot
Haw2_Plot
```

## Potential Additional Sites
```{r}
# 02096846- Cane Creek near Orange Grove, NC
# 02098197- B. Everett Jordan Lake at Dam near Moncure, NC
```

